### ISSUE TITLE
Feature request: terminal commands

### ISSUE THREAD

**Issue by ieatacid** [Salandora/OctoPrint-EditorCollection#2]
Is it possible to add an option to add custom command buttons to the terminal window?

For example, one command button I use sends the m code for end stop status but it's on the control page so I have to switch to the the control page, press button, then switch back to the terminal page to view the output.

**Comment by Salandora** [comment]
Well there is actually no easy way to do it.

But you could use feedback commands.

Also this is the wrong bug tracker ^^ you most likely wanted to put this into the customControls bug tracker. 
But it would be better to e.g. join the IRC chat and ask for help there, or at the goolge plus community maybe.
([octoprint.org](octoprint.org) look at the bottom at Contact)

**Comment by ieatacid** [comment]
Ok thanks. Sorry about that.
